# Generated by Django 4.0.5 on 2022-06-04 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vk_bot', '0002_collection_image_game_vkuser_current_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='vk_bot.collection'),
        ),
    ]
