# Generated by Django 4.0.5 on 2022-06-04 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vk_bot', '0003_alter_image_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('created', 'created'), ('started', 'started'), ('finished', 'finished')], default='created', max_length=400),
        ),
    ]
