# Generated by Django 4.0.5 on 2022-06-04 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vk_bot', '0004_game_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='single',
            field=models.BooleanField(default=False),
        ),
    ]
