# Generated by Django 4.0.5 on 2022-06-04 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vk_bot', '0005_game_single'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(db_index=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='vk_bot.image')),
            ],
            options={
                'verbose_name': 'Слово изображения',
                'verbose_name_plural': 'Слова изображения',
                'ordering': ['-update_date'],
            },
        ),
    ]
