# Generated by Django 4.0.5 on 2022-06-04 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vk_bot', '0006_imageword'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='used_images',
            field=models.ManyToManyField(blank=True, to='vk_bot.image'),
        ),
    ]
