# Generated by Django 4.0.5 on 2022-06-04 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vk_bot', '0007_game_used_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='current_images',
            field=models.ManyToManyField(blank=True, related_name='current_images', to='vk_bot.image'),
        ),
    ]
