# Generated by Django 4.0.5 on 2022-06-04 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vk_bot', '0008_game_current_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='current_correct_answer',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
