# Generated by Django 4.0.5 on 2022-06-04 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vk_bot', '0009_game_current_correct_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='stage',
            field=models.CharField(choices=[('getting_answers', 'getting_answers'), ('distribution_of_cards', 'distribution_of_cards')], default='distribution_of_cards', max_length=400),
        ),
    ]
