# Generated by Django 4.0.5 on 2022-06-04 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vk_bot', '0010_game_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='vkuser',
            name='current_score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
