# Generated by Django 4.0.5 on 2022-06-04 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vk_bot', '0012_alter_vkuser_current_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='words',
        ),
        migrations.AddField(
            model_name='collection',
            name='album_url',
            field=models.TextField(blank=True),
        ),
    ]
