# Generated by Django 4.0.5 on 2022-06-04 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vk_bot', '0013_remove_collection_words_collection_album_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='current_attachment_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='current_word',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
