# Generated by Django 4.0.5 on 2022-06-04 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vk_bot', '0015_vkuser_answered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vk_bot.collection'),
        ),
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('creating', 'creating'), ('waiting', 'waiting'), ('started', 'started'), ('finished', 'finished')], default='created', max_length=400),
        ),
    ]
