# Generated by Django 4.0.5 on 2022-06-04 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vk_bot', '0016_alter_game_collection_alter_game_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='created_games', to='vk_bot.vkuser'),
            preserve_default=False,
        ),
    ]
