# Generated by Django 4.0.5 on 2022-06-05 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vk_bot', '0017_game_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='with_host',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vkuser',
            name='cards_in_hand',
            field=models.ManyToManyField(blank=True, related_name='cards_in_hand', to='vk_bot.image'),
        ),
        migrations.AddField(
            model_name='vkuser',
            name='current_card_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vkuser',
            name='is_game_host',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vkuser',
            name='was_game_circle_host',
            field=models.BooleanField(default=False),
        ),
    ]
