# Generated by Django 4.0.5 on 2022-06-05 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vk_bot', '0018_game_with_host_vkuser_cards_in_hand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vkuser',
            name='sent_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sent_cards', to='vk_bot.image'),
        ),
        migrations.AlterField(
            model_name='game',
            name='stage',
            field=models.CharField(choices=[('game_host_writing_word', 'game_host_writing_word'), ('sending_word', 'sending a word'), ('send_cards', 'send_cards'), ('getting_answers', 'getting_answers'), ('distribution_of_cards', 'distribution_of_cards')], default='distribution_of_cards', max_length=400),
        ),
    ]
