# Generated by Django 4.0.5 on 2022-06-05 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vk_bot', '0019_vkuser_sent_card_alter_game_stage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vkuser',
            old_name='current_card_number',
            new_name='answer',
        ),
    ]
